# This file was generated by GoReleaser. DO NOT EDIT.
cask "claviger" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "aed0f7929696b397eae6cef82657d049d800f3bc3085b378f3784e7d2cd157ec"
      url "https://github.com/Su1ph3r/claviger/releases/download/v#{version}/claviger_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f245cd41086af68af4dfc19d6b861317a0bea342e66573b5f7aa6f320f5115c8"
      url "https://github.com/Su1ph3r/claviger/releases/download/v#{version}/claviger_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "31c7f365644926529bfdd01991a23f33c6ea419d6f0ba0a1b2c1626b28d1c1ab"
      url "https://github.com/Su1ph3r/claviger/releases/download/v#{version}/claviger_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4a9a9c456cf4388ef5876a442296393fd9d0d587644cf4b654844ba6d7562f0b"
      url "https://github.com/Su1ph3r/claviger/releases/download/v#{version}/claviger_#{version}_linux_amd64.tar.gz"
    end
  end

  name "claviger"
  desc "Session authority for penetration testers."
  homepage "https://github.com/Su1ph3r/claviger"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claviger"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claviger"]
    end
  end

  # No zap stanza required
end
