# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claviger < Formula
  desc "Session authority for penetration testers."
  homepage "https://github.com/Su1ph3r/claviger"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Su1ph3r/claviger/releases/download/v1.0.0/claviger_1.0.0_darwin_amd64.tar.gz"
      sha256 "4c6b3c9b6b2a112e3485cb64b0c4fbe1fc0aae4d6f9982e28ba98c947002f1ad"

      define_method(:install) do
        bin.install "claviger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Su1ph3r/claviger/releases/download/v1.0.0/claviger_1.0.0_darwin_arm64.tar.gz"
      sha256 "7a7b690137597c35f9461878bfc0810e7c1abea3328c04c74cf76b06521a9f1b"

      define_method(:install) do
        bin.install "claviger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Su1ph3r/claviger/releases/download/v1.0.0/claviger_1.0.0_linux_amd64.tar.gz"
      sha256 "c125a5061d95a3b0c9ab2011a7b7f091fa18a8a7780b3c4ce89e008b4f834590"
      define_method(:install) do
        bin.install "claviger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Su1ph3r/claviger/releases/download/v1.0.0/claviger_1.0.0_linux_arm64.tar.gz"
      sha256 "235f09417eada24466099c60d9e4c53adf485241aaceef275653eb78e8e03078"
      define_method(:install) do
        bin.install "claviger"
      end
    end
  end

  test do
    system "#{bin}/claviger", "version"
  end
end
